xcassets:
    inputs: Sources/AdmiralCalendarSwiftUI/Resources/Assets/Symbols.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: Sources/AdmiralCalendarSwiftUI/Classes/Assets/Symbols.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: AssetSymbol
